package jackpi.client;

import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Levin
 */
public class Gui extends javax.swing.JFrame
{

  TableModel tm;

  /**
   * Creates new form Gui
   */
  public Gui()
  {
    initComponents();
    super.setTitle("Calculating useless electronics");
    tm = new TableModel();
    jTable.setModel(tm);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    jScrollPane1 = new javax.swing.JScrollPane();
    jTable = new javax.swing.JTable();
    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jSpinner1 = new javax.swing.JSpinner();
    jLabel2 = new javax.swing.JLabel();
    jSpinner2 = new javax.swing.JSpinner();
    jButton1 = new javax.swing.JButton();
    jCalc = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setMinimumSize(new java.awt.Dimension(700, 500));

    jTable.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][]
      {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String []
      {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    jScrollPane1.setViewportView(jTable);

    getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

    jLabel1.setText("R1");
    jPanel1.add(jLabel1);

    jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 999999.0d, 1.0d));
    jPanel1.add(jSpinner1);

    jLabel2.setText("R2");
    jPanel1.add(jLabel2);

    jSpinner2.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 999999.0d, 1.0d));
    jPanel1.add(jSpinner2);

    jButton1.setText("Hinzufügen");
    jButton1.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        jButton1ActionPerformed(evt);
      }
    });
    jPanel1.add(jButton1);

    jCalc.setText("Berechnen");
    jCalc.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        jCalcActionPerformed(evt);
      }
    });
    jPanel1.add(jCalc);

    getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jCalcActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jCalcActionPerformed
  {//GEN-HEADEREND:event_jCalcActionPerformed
    calc();
  }//GEN-LAST:event_jCalcActionPerformed

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
  {//GEN-HEADEREND:event_jButton1ActionPerformed
    add();
  }//GEN-LAST:event_jButton1ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try
    {
      for(javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
      {
        if("Nimbus".equals(info.getName()))
        {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    }
    catch (ClassNotFoundException ex)
    {
      java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (InstantiationException ex)
    {
      java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (IllegalAccessException ex)
    {
      java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (javax.swing.UnsupportedLookAndFeelException ex)
    {
      java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable()
    {

      public void run()
      {
        new Gui().setVisible(true);
      }

    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jCalc;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JSpinner jSpinner1;
  private javax.swing.JSpinner jSpinner2;
  private javax.swing.JTable jTable;
  // End of variables declaration//GEN-END:variables

  private void calc()
  {
    for(int i = 0; i < tm.getRowCount(); i++)
    {
      try
      {
        double res = JackPiClient.getData(tm.getDoubleAt(i, 0), tm.getDoubleAt(i, 1));

        tm.setValueAt(res, i, 2);
        //System.out.println("Value at: " + tm.getValueAt(i, 2));
        
      }
      catch (IOException ex)
      {
        JOptionPane.showMessageDialog(this, "Error!" + ex.getLocalizedMessage());
      }
      catch (Exception ex)
      {
      }
    }
    tm.fireTableDataChanged();
  }

  private void add()
  {
    
    tm.add((double)jSpinner1.getValue(), (double)jSpinner2.getValue());
    tm.fireTableDataChanged();
  }

}
